#!/usr/bin/env bash
# Sage Homeschool Tutor — first-run setup wizard
# Usage: bash setup.sh   (or: make setup)
set -euo pipefail

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
RESET='\033[0m'

info()    { echo -e "${CYAN}▶  $*${RESET}"; }
success() { echo -e "${GREEN}✓  $*${RESET}"; }
warn()    { echo -e "${YELLOW}⚠  $*${RESET}"; }
error()   { echo -e "${RED}✗  $*${RESET}"; exit 1; }
blank()   { echo ""; }

# ── Banner ────────────────────────────────────────────────────────────────────
blank
echo -e "${BOLD}╔══════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║      Sage Homeschool Tutor — Setup       ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════════╝${RESET}"
blank

# ── Prerequisites ─────────────────────────────────────────────────────────────
info "Checking prerequisites..."
command -v docker >/dev/null 2>&1     || error "Docker is not installed. Visit https://docs.docker.com/get-docker/"
command -v openssl >/dev/null 2>&1    || error "openssl is not installed."
docker compose version >/dev/null 2>&1 || error "Docker Compose v2 is required. Update Docker Desktop or install the plugin."
success "Docker and Compose found"

# ── Existing .env ─────────────────────────────────────────────────────────────
if [[ -f .env ]]; then
  warn ".env already exists."
  read -rp "   Overwrite it and start fresh? [y/N] " OVERWRITE
  [[ "${OVERWRITE,,}" == "y" ]] || { info "Keeping existing .env. Run 'make start' to launch."; exit 0; }
  cp .env .env.backup
  success "Existing .env backed up to .env.backup"
fi

blank
echo -e "${BOLD}Let's collect the required values.${RESET}"
echo -e "Press Enter to skip optional fields."
blank

# ── Anthropic API key ─────────────────────────────────────────────────────────
info "1/5  Anthropic (Claude) API key"
echo "     Get yours at: https://console.anthropic.com/"
while true; do
  read -rp "     ANTHROPIC_API_KEY: " ANTHROPIC_API_KEY
  [[ -n "$ANTHROPIC_API_KEY" ]] && break
  warn "This field is required."
done

# ── Database URL ──────────────────────────────────────────────────────────────
blank
info "2/5  Managed PostgreSQL database URL"
echo "     Supported providers: Neon (free tier), Supabase, Railway, Render"
echo "     Format: postgresql+asyncpg://user:pass@host/dbname?ssl=require"
while true; do
  read -rp "     DATABASE_URL: " DATABASE_URL
  [[ -n "$DATABASE_URL" ]] && break
  warn "This field is required."
done

# ── Access credentials ────────────────────────────────────────────────────────
blank
info "3/5  Parent password (admin login)"
while true; do
  read -rsp "     PARENT_PASSWORD: " PARENT_PASSWORD; echo
  [[ ${#PARENT_PASSWORD} -ge 8 ]] && break
  warn "Must be at least 8 characters."
done

blank
info "4/5  Child PIN (student login, 4+ digits)"
while true; do
  read -rp "     CHILD_PIN: " CHILD_PIN
  [[ "$CHILD_PIN" =~ ^[0-9]{4,}$ ]] && break
  warn "Must be 4 or more digits."
done

# ── Auto-generate secrets ─────────────────────────────────────────────────────
blank
info "5/5  Generating cryptographic secrets..."
SECRET_KEY=$(openssl rand -hex 32)
MASTER_SECRET=$(openssl rand -hex 32)
success "SECRET_KEY and MASTER_SECRET generated (64 hex chars each)"

# ── Detect LAN IP for tablet access ──────────────────────────────────────────
LAN_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
if [[ -n "$LAN_IP" ]]; then
  CORS_ORIGINS="https://localhost,https://${LAN_IP},http://ui:80"
  success "Detected LAN IP: ${LAN_IP} — tablets can reach Sage at https://${LAN_IP}"
else
  CORS_ORIGINS="https://localhost,http://ui:80"
  warn "Could not detect LAN IP. Add it to CORS_ORIGINS in .env if needed."
fi

# ── Write .env ────────────────────────────────────────────────────────────────
blank
info "Writing .env..."
cat > .env <<EOF
# Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
# DO NOT commit this file — it contains secrets.

ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
SECRET_KEY=${SECRET_KEY}
MASTER_SECRET=${MASTER_SECRET}
PARENT_PASSWORD=${PARENT_PASSWORD}
CHILD_PIN=${CHILD_PIN}
DATABASE_URL=${DATABASE_URL}
CORS_ORIGINS=${CORS_ORIGINS}
DISABLE_API_DOCS=true
PRODUCTION=true
EOF
chmod 600 .env
success ".env written (mode 600 — only readable by you)"

# ── Start services ────────────────────────────────────────────────────────────
blank
echo -e "${BOLD}Starting Sage...${RESET}"
docker compose up -d --build

# ── Wait for health ───────────────────────────────────────────────────────────
blank
info "Waiting for the API to become healthy (up to 90 s)..."
DEADLINE=$((SECONDS + 90))
until curl -skf https://localhost/api/health >/dev/null 2>&1; do
  if [[ $SECONDS -ge $DEADLINE ]]; then
    warn "API did not respond in time. Check logs with: make logs"
    break
  fi
  printf "."
  sleep 2
done
echo ""

if curl -skf https://localhost/api/health >/dev/null 2>&1; then
  success "API is healthy!"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
blank
echo -e "${BOLD}${GREEN}══════════════════════════════════════════${RESET}"
echo -e "${BOLD}${GREEN}  Sage is running!${RESET}"
echo -e "${BOLD}${GREEN}══════════════════════════════════════════${RESET}"
blank
echo "  Open in your browser:  https://localhost"
if [[ -n "$LAN_IP" ]]; then
  echo "  From tablets on your network: https://${LAN_IP}"
  echo "  (Run 'make caddy-trust' to install the cert on each tablet — no more warnings)"
fi
echo "  Log in as parent with: PARENT_PASSWORD you just set"
blank
echo "  Useful commands:"
echo "    make status    — check container health"
echo "    make logs      — tail live logs"
echo "    make stop      — shut down"
echo "    make help      — all available commands"
blank
